name: check
on: [pull_request, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - name: Check formatting
        run: nix fmt -- --ci
      - name: Build system closure
        run: nix build .#darwinConfigurations.MacBook-Air-de-Pierre.system
